# Generated by Django 4.2.27 on 2026-01-22 18:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_code', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('profile_photo', models.ImageField(upload_to='users/photos/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make_model', models.CharField(help_text='e.g. Autoturism / DACIA / LOGAN', max_length=200)),
                ('registration_number', models.CharField(max_length=20)),
                ('vin', models.CharField(max_length=50)),
                ('engine_power', models.CharField(help_text='e.g. 1390 cm3 / 55 kW', max_length=100)),
                ('seats_mass', models.CharField(help_text='e.g. 5 locuri / 1500 kg', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='badges.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer_name', models.CharField(default='INSURANCE CO. S.A.', max_length=100)),
                ('insurer_cui', models.CharField(default='RO12345678', max_length=20)),
                ('insurer_tel_fax', models.CharField(default='021.123.45.67', max_length=50)),
                ('series', models.CharField(default='RO/01', max_length=10)),
                ('number', models.CharField(max_length=20)),
                ('header_nr', models.CharField(max_length=20)),
                ('branch_agency', models.CharField(default='Bucharest Agency 1', max_length=100)),
                ('broker_name', models.CharField(default='Best Broker SRL', max_length=100)),
                ('broker_code', models.CharField(default='BRK-001', max_length=20)),
                ('validity_start', models.DateField()),
                ('validity_end', models.DateField()),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direct_settlement_premium', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installments_count', models.CharField(default='Integral', max_length=50)),
                ('valoare_rate', models.CharField(default='-', max_length=50)),
                ('due_dates', models.CharField(default='-', max_length=100)),
                ('incasata_cu', models.CharField(default='OP', max_length=50)),
                ('in_data_de', models.DateField(blank=True, null=True)),
                ('bonus_malus', models.CharField(default='B0', max_length=10)),
                ('limit_bodily_injury', models.CharField(default='6.070.000 EURO', max_length=50)),
                ('limit_property_damage', models.CharField(default='1.220.000 EURO', max_length=50)),
                ('additional_services', models.TextField(blank=True, default='Asistenta Rutiera (Basic)')),
                ('observations', models.TextField(blank=True, default='Polita emisa electronic.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='badges.userprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='IdentityCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.CharField(default='XR', max_length=5)),
                ('number', models.CharField(max_length=10)),
                ('cnp', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('nationality', models.CharField(default='Romana', max_length=100)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('place_of_birth', models.CharField(help_text='Place of birth (Location)', max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('issued_by', models.CharField(default='SPCLEP', max_length=100)),
                ('validity_start', models.DateField()),
                ('validity_end', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_cards', to='badges.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='BadgeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ai_prompt_modifiers', models.JSONField(default=dict)),
                ('ai_altered_face', models.ImageField(blank=True, null=True, upload_to='badges/temp_faces/')),
                ('final_badge', models.ImageField(blank=True, null=True, upload_to='badges/final/')),
                ('status', models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badges.userprofile')),
            ],
        ),
    ]
