# Generated by Django 4.2.27 on 2026-01-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_alter_userprofile_id_code_alter_userprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancepolicy',
            name='policy_document',
            field=models.ImageField(blank=True, null=True, upload_to='insurance_policies/'),
        ),
    ]
