# Generated by Django 4.2.27 on 2026-01-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0004_insurancepolicy_policy_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgerequest',
            name='source_image',
            field=models.ImageField(blank=True, null=True, upload_to='badges/temp/'),
        ),
    ]
