// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALEfs8Rg2oD81AwFms5KuKjrtFTzQlUfg',
    appId: '1:340647813489:web:4fab1bbf7811d5293e96d0',
    messagingSenderId: '340647813489',
    projectId: 'fast-and-dubious',
    authDomain: 'fast-and-dubious.firebaseapp.com',
    storageBucket: 'fast-and-dubious.firebasestorage.app',
    measurementId: 'G-8CNTY5VL0G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_e0MEnro2DumkHueO6Z5Hojiz91KxT_g',
    appId: '1:340647813489:android:9813cba343f4797a3e96d0',
    messagingSenderId: '340647813489',
    projectId: 'fast-and-dubious',
    storageBucket: 'fast-and-dubious.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf6X0m_vUu1pQKFcB1oGTwKcx7hpRfnkY',
    appId: '1:340647813489:ios:53a377015588c9863e96d0',
    messagingSenderId: '340647813489',
    projectId: 'fast-and-dubious',
    storageBucket: 'fast-and-dubious.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
